/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "tertiary-fixed": "#9eabff",
              "on-surface": "#f1f3fc",
              "secondary-dim": "#ff56ef",
              "on-primary-fixed-variant": "#005e64",
              "primary-fixed": "#00eefc",
              "surface-container-high": "#1b2028",
              "tertiary": "#8596ff",
              "on-tertiary": "#001269",
              "error": "#ff716c",
              "on-background": "#f1f3fc",
              "on-surface-variant": "#a8abb3",
              "on-secondary-fixed-variant": "#93008c",
              "inverse-on-surface": "#51555c",
              "tertiary-fixed-dim": "#8d9cff",
              "secondary-fixed-dim": "#ffa7ed",
              "primary-fixed-dim": "#00deec",
              "surface-container-lowest": "#000000",
              "error-container": "#9f0519",
              "surface-dim": "#0a0e14",
              "on-error": "#490006",
              "outline": "#72757d",
              "background": "#0a0e14",
              "error-dim": "#d7383b",
              "surface": "#0a0e14",
              "surface-variant": "#20262f",
              "on-secondary": "#41003d",
              "tertiary-container": "#3956fb",
              "surface-tint": "#8ff5ff",
              "secondary-container": "#ab00a2",
              "on-primary-container": "#005359",
              "on-primary": "#005d63",
              "surface-container-highest": "#20262f",
              "on-tertiary-fixed-variant": "#0023ab",
              "on-secondary-fixed": "#63005e",
              "surface-container": "#151a21",
              "outline-variant": "#44484f",
              "on-tertiary-container": "#ffffff",
              "inverse-primary": "#006a71",
              "on-primary-fixed": "#003f43",
              "secondary": "#ff56ef",
              "primary": "#8ff5ff",
              "primary-container": "#00eefc",
              "on-secondary-container": "#fff5f9",
              "secondary-fixed": "#ffbdef",
              "tertiary-dim": "#4963ff",
              "inverse-surface": "#f8f9ff",
              "surface-bright": "#262c36",
              "on-error-container": "#ffa8a3",
              "on-tertiary-fixed": "#000c54",
              "primary-dim": "#00deec",
              "surface-container-low": "#0f141a"
      },
      "fontFamily": {
              "headline": ["Space Grotesk", "sans-serif"],
              "body": ["Manrope", "sans-serif"],
              "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
